JamesPartsafas/online-store

- amaznot/app/Http/Controllers/HomeController.php
- amaznot/app/Http/Controllers/ListController.php
- amaznot/database/seeders/ProductSeeder.php
- amaznot/public/css/styles.css
- amaznot/resources/views/pages/index.blade.php
- amaznot/resources/views/pages/productlist.blade.php
- amaznot/routes/web.php
On request, user is provided with product list for specific category. Also allows for pagination and querying by subcategory.
> Provide product lists to user

- amaznot/app/Http/Controllers/LoginController.php
Login checks ensures that when a user is signed, they will be riderected to home if they attempt to go back to the login or register pages. 
Admin check is to differentiate between normal user and administrator. For now both are riderected to home page
> Made a login check & Admin account check  

- amaznot/app/Http/Controllers/AdminController.php
- amaznot/app/Http/Controllers/Controller.php
- amaznot/app/Http/Controllers/LoginController.php
- amaznot/app/Http/Controllers/LogoutController.php
- amaznot/app/Http/Controllers/RegisterController.php
- amaznot/resources/views/auth/register.blade.php
- amaznot/resources/views/pages/admin/addproduct.blade.php
- amaznot/routes/web.php
Implement necessary controller methods and a basic form for administrators to upload new item data. Also implement means to verify identity of administrator in these controller methods.
> Allow administrator to add products to database

- amaznot/app/Http/Controllers/RegisterController.php
- amaznot/app/Models/User.php
- amaznot/resources/views/auth/login.blade.php
- Registered users 'name' must be unique or registration fails and "This name is already taken" is displayed.
- Requirements are moved to the validation, instead of fillable
- Solution fixed issue #73 
-
> Fixed User Registration Problem

- amaznot/tests/Feature/ExampleTest.php
- laravel.yml
Allow for automated tests from PHPUnit to be run on pull request.
> #50 create yml file to run tests

- amaznot/resources/views/auth/register.blade.php
Styles still need to be worked on, but all functionalities are present.
> Created signup frontend page 

- amaznot/resources/views/auth/login.blade.php
- amaznot/resources/views/auth/register.blade.php
Styles still need to be worked on, but all functionalities are present.
> Created login page for frontend

- amaznot/app/Http/Controllers/ListController.php
- amaznot/public/css/styles.css
- amaznot/resources/views/pages/productlist.blade.php
- amaznot/routes/web.php
- Sorting by sub-category has been set up.
- Link to product page is provided.
- Basic styles can be modified and changed later as required.
> Created aisles page for frontend

- amaznot/app/Http/Controllers/ProductController.php
- amaznot/database/seeders/ProductSeeder.php
- amaznot/public/js/script.js
- amaznot/resources/views/layouts/layout.blade.php
- amaznot/resources/views/pages/productpage.blade.php
Create cart functionality for the product page, allowing signed in users to add or remove items from their cart.
> #89 Handle cart functionality on the product page

- amaznot/package-lock.json
- amaznot/resources/views/pages/admin/addproduct.blade.php
Implement styles for the admin add product page, in line with site standards
> #78 added admin add product page (frontend)

- amaznot/app/Models/User.php
- amaznot/app/Providers/AppServiceProvider.php
- amaznot/app/Providers/HeaderStaticData.php
- amaznot/public/css/styles.css
- amaznot/public/js/script.js
- amaznot/resources/views/layouts/layout.blade.php
Added the header (navbar) and the footer. None of the data is hardcoded. 
In case an error occurred during the process of retrieving the categories and subcategories from the DB, a copy of those data will be served. 
The information in the footer can be changed and not finalized.
> #53-create-frontend-layout

- amaznot/app/Http/Controllers/ListController.php
- Changed the number of products per page (from 10 to 12).
> #56 Aisles Page

- amaznot/public/css/styles.css
- amaznot/public/js/script.js
- amaznot/resources/views/layouts/layout.blade.php
- amaznot/resources/views/pages/index.blade.php
- amaznot/resources/views/pages/productpage.blade.php
- #98 resolved bad links
- #88 resolved varying title lengths
- resolved JS bug on product page
- removed placeholder texts for header/footer
- reclassed generic css/bootstrap classes
- added sitewide styling
- added links to promo images
> #98 fixing bugs on homepage

- amaznot/resources/views/pages/productpage.blade.php
The quantity indicator on the product page has been modified to include a color.
> #54 added color to  the quantity

- amaznot/app/Http/Controllers/OrderController.php
- amaznot/app/Models/Order.php
- amaznot/app/Models/OrderItem.php
- amaznot/database/migrations/2022_02_19_182156_create_orders_table.php
- amaznot/database/migrations/2022_02_19_194037_create_order_items_table.php
- amaznot/resources/views/pages/cart.blade.php
- amaznot/resources/views/pages/orders.blade.php
- amaznot/routes/web.php
Implement necessary data models and controller methods to track user purchases and subsequently clear user cart.
> #93 Track user purchases

- amaznot/resources/views/pages/productpage.blade.php
#113
Code was duplicated in product page blade.
> Bugfix for description not displaying correctly

- amaznot/app/Http/Controllers/HomeController.php
- amaznot/resources/views/layouts/layout.blade.php
- amaznot/resources/views/pages/disclaimer.blade.php
- amaznot/resources/views/pages/index.blade.php
- amaznot/routes/web.php
#81
Added routing for disclaimer page
Created disclaimer page
> Created disclaimer page

- amaznot/public/css/styles.css
- amaznot/resources/views/layouts/layout.blade.php
- amaznot/resources/views/pages/contactus.blade.php
#117 
Added Contact Us page to header and footer.
Revised footer links and moves issues to Sprint4, as appropriate.
> 117 contact us page

- amaznot/public/css/styles.css
- amaznot/public/js/script.js
- amaznot/resources/views/layouts/layout.blade.php
- amaznot/resources/views/pages/orders.blade.php
- amaznot/resources/views/pages/ordersitems.blade.php
Added the orders history page with the ability to view the products purchased. The JS is compatible with IE6
> #96-add-order-history-page

- README.md
- amaznot/public/js/script.js
- amaznot/resources/views/pages/cart.blade.php
- amaznot/resources/views/pages/productpage.blade.php
added style to the cart page that matches the product page.
> 111 finish the cart page 

- amaznot/app/Http/Controllers/SearchController.php
- amaznot/resources/views/pages/search.blade.php
- amaznot/routes/web.php
- amaznot/tests/Feature/SearchTest.php
- Should Perform searching on the product page
- Fuzzy search checks written string (does not have to be full text) and displays all matching products
> #121 Made Version 1 of Fuzzy Search

- amaznot/app/Http/Controllers/SearchController.php
- amaznot/composer.json
- amaznot/composer.lock
- amaznot/resources/views/layouts/layout.blade.php
- amaznot/resources/views/pages/search.blade.php
- amaznot/routes/web.php
- amaznot/tests/Feature/SearchTest.php
- Added search bar
- Modified search route from GET to POST
- Modified search tests
- Modified SeachController.php to return query
- Added search page (frontend)
> 122 add search page
